[[alunos]]
id = 1
nome = "tomas"

[[alunos]]
id = 2
nome = "renato"

[[alunos]]
id = 3
nome = "joao"

[[comments]]
id = 1
text = "comment 1"
postId = 1

[[comments]]
id = 2
text = "comment 2"
postId = 2
