title = "TOML Example"
title2 = "TOML2 Example2"
ola = 1
name = "Tom Preston Werner"
[mecago]
teofilo="TODO"
lines = '''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''
str3 = """\
       The quick brown \
       fox jumps over \
       the lazy dog\
       """

[peidinho]
teofilo="barraca"
flt1 = +1.0
flt2 = 3.1415
flt3 = -0.01

# exponent
flt4 = 5e+22
flt5 = 1e06
flt6 = -2E-2

# both
flt8 = 224_617.445_991_228

[meu]
server = "I'm a string. \"You can quote me\". Name\tJos\u00E9."
siu= [ 1, 3,[ "ola", "filho"], 5]
message="\u0068\u0065\u006c\u006c\u006f \u0077\u006f\u0072\u006c\u0064"

[meu.nome]
ok=true
madre= "porque"
[meu.nome.estupido]
esfincter= 23
nome ="joao"
time = 1979-05-27T07:32:00Z
time2 = 1979-05-27
str4 = """Here are two quotation marks: "". Simple enough."""
str5 = """Here are three quotation marks: ""\"."""
str6 = """Here are fifteen quotation marks: ""\"""\"""\"""\"""\"."""

# "This," she said, "is just a pointless statement."
str7 = """"This," she said, "is just a pointless statement"."""
winpath = 'C:\Users\nodejs\templates'
str = ''''That,' she said, 'is still pointless'.'''